import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DGital - Digital Agency HTML Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

    <head>
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    {/* <!-- Favicon --> */}
    <link href="img/favicon.ico" rel="icon" />

    {/* <!-- Google Web Fonts --> */}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&family=Jost:wght@500;600;700&display=swap" rel="stylesheet" /> 

    {/* <!-- Icon Font Stylesheet --> */}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

    {/* <!-- Libraries Stylesheet --> */}
    <link href="lib/animate/animate.min.css" rel="stylesheet" />
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet" />

    {/* <!-- Customized Bootstrap Stylesheet --> */}
    <link href="css/bootstrap.min.css" rel="stylesheet" />

    {/* <!-- Template Stylesheet --> */}
    <link href="css/style.css" rel="stylesheet" />


    {/* <!-- JavaScript Libraries --> */}
    <Script src="https://code.jquery.com/jquery-3.4.1.min.js"></Script>
    <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></Script>
    <Script src="lib/wow/wow.min.js"></Script>
    <Script src="lib/easing/easing.min.js"></Script>
    <Script src="lib/waypoints/waypoints.min.js"></Script>
    <Script src="lib/counterup/counterup.min.js"></Script>
    <Script src="lib/owlcarousel/owl.carousel.min.js"></Script>
    <Script src="lib/isotope/isotope.pkgd.min.js"></Script>
    <Script src="lib/lightbox/js/lightbox.min.js"></Script>

    {/* <!-- Template JavaScript --> */}
    <Script src="js/main.js"></Script>








    </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
